apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pibisi-ingress
  annotations:
     kubernetes.io/ingress.class: "custom-nginx"  # Usa il controller personalizzato
spec:
  ingressClassName: custom-nginx	
  rules:
  - host: api.aegisx.cloud  # Sostituisci con il tuo dominio
    http:
      paths:
      - path: /pibisi
        pathType: Prefix
        backend:
          service:
            name: pibisi-service
            port:
              number: 8080