name: Build & Push on Tag

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout progetto A (my-app)
        uses: actions/checkout@v3

      - name: Checkout libreria B (my-lib)
        uses: actions/checkout@v3
        with:
          repository: mirdan2024/commonBase
          path: commonBase
          token: ${{ secrets.GH_PAT }}
          
      - name: Estrai tag e repository lowercase
        id: vars
        run: |
          echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          echo "REPO_LOWER=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Installa libreria B localmente
        run: |
          cd commonBase
          mvn clean install -DskipTests
          cd ..

      - name: Build progetto A
        run: mvn clean package -DskipTests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login a GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}

      - name: Estrai tag
        id: extract_tag
        run: |
          echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Build & Push immagine Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ steps.vars.outputs.REPO_LOWER }}:${{ steps.vars.outputs.TAG }}
